### ISSUE TITLE
View Restaurant 

### ISSUE THREAD

**Issue by DFCMK** [DFCMK/django-reservation-system#7]
As a customer, I want to be able to view the restaurant , including photos, menus, opening hours, and reviews.

### Acceptance Criteria

- Give logged in users ability to give feedback

- Landing page with a inviting Background image and Information about the Restaurant as Text overlay

- View Menu

- View images from Food and location

### Task:
- [ ] Create Landing Page similar to Budapest Homepage, maybe choose an existing layout from Bootstrap
- [ ] Create about page which should contain brief summery about the restaurant itself
- [ ] create a page for displaying only the Menu.
- [ ] create a Gallery with Review section, where verified costumers can view reviews from other people and write a own one.
